# Generated by Django 3.2.5 on 2021-07-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='M', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooling.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooling.student')),
            ],
        ),
    ]
