# Generated by Django 3.2.5 on 2021-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schooling", "0002_matriculation")]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="personal_doc",
            field=models.CharField(max_length=11, unique=True),
        )
    ]
