# Generated by Django 3.1.3 on 2021-07-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schooling", "0004_auto_20210706_2112")]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(default="", max_length=11),
        )
    ]
